---
- name: Appsilon
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Create nice-script.sh locally
    copy:
      dest: "/home/vboxuser/ansible-playbooks/nice-script.sh"
      content: |
        #!/bin/bash
        echo "$(cat /proc/mounts)"
  - name: Copy nice-script.sh to remote machine, directory /etc/skel
    become: true
    copy:
      src: "/home/vboxuser/ansible-playbooks/nice-script.sh"
      dest: "/etc/skel"
      owner: vboxuser
      group: vboxuser
      mode: 0744
  - name: Create user
    become: true
    ansible.builtin.user:
      name: john
      groups: sudo
      state: present
      uid: 1234
      create_home: true
      home: "/better-place/john"
  - name: Grant passwordless sudo to created user
    become: true
    copy:
      dest: /etc/sudoers.d/80-ansible-sudo-user
      content: "john ALL=(ALL) NOPASSWD:ALL"
      mode: 0440
  - name: Install package Tmux
    become: true
    ansible.builtin.package:
      name: tmux
      state: present
  - name: Install package Vim
    become: true
    ansible.builtin.package:
      name: vim
      state: present
  - name: "Install Terraform CLI - Part 1"
    ansible.builtin.shell:
      cmd: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - name: "Install Terraform CLI - Part 2"
    ansible.builtin.shell:
      cmd: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  - name: "Install Terraform CLI - Part 3 - Install Terraform"
    ansible.builtin.apt:
      name: terraform
      state: present
